getwd()
ls() # objects in workspace
list.files() # or dir()
?list.files()
list.dirs()
args(list.files)
old.dir <- getwd()
dir.create('testdir')
setwd('testdir')
file.create('mytest.R')
list.files()
file.exists('mytest.R')
file.info('mytest.R')
file.rename(from='mytest.R', to='mytest2.R')
file.copy(from='mytest2.R', to='mytest3.R')
file.path('folder_name','sub_folder_name')
dir.create(file.path('testdir2', 'testdir3'), recursive = TRUE)
dir.create(file.path('testdir2', 'testdir3'), recursive = FALSE)
setwd(old.dir)
unlink('testdir',recursive = TRUE)
